# Generated by Django 4.2.11 on 2024-06-07 20:38

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to=products.models.upload_to),
        ),
    ]
